### ISSUE TITLE
CLI: (i) create, (ii) document

### ISSUE THREAD

**Issue by joeflack4** [INCATools/kgcl-tools#24]
## Description
I'm not might have missed it, but I'm looking through the code and docs for a CLI, but not seeing one.

Not sure yet how to use the tool.

**Comment by jamesaoverton** [comment]
A lot of work was done on PR #11 and this branch: https://github.com/ckindermann/knowledge-graph-change-language/tree/parser

It includes documentation here: https://github.com/ckindermann/knowledge-graph-change-language/blob/parser/kgcl/README.md

We were hoping for @matentzn and/or @cmungall to review and approve that, but they have not had time.

**Comment by joeflack4** [comment]
@jamesaoverton Oh ok thanks, james. If you could link this issue to that PR that would be good, but not necessary. I'll give this a look

**Comment by cmungall** [comment]
PRs are merged

**Comment by joeflack4** [comment]
Thanks, Chris!
